export const markdownStyles = {
    a: ({ node, ...props }) => <a {...props} target="_blank" rel="noopener noreferrer" className="text-indigo-500" />,
    h1: ({ node, ...props }) => <h1 {...props} className="text-2xl font-semibold" />,
    h2: ({ node, ...props }) => <h2 {...props} className="text-xl font-semibold" />,
    h3: ({ node, ...props }) => <h3 {...props} className="text-lg font-semibold" />,
    h4: ({ node, ...props }) => <h4 {...props} className="text-base font-semibold" />,
    h5: ({ node, ...props }) => <h5 {...props} className="text-base font-semibold" />,
    h6: ({ node, ...props }) => <h6 {...props} className="text-base font-semibold" />,
    p: ({ node, ...props }) => <p {...props} className="text-base" />,
    em: ({ node, ...props }) => <em {...props} />,
    strong: ({ node, ...props }) => <strong {...props} />,
    blockquote: ({ node, ...props }) => <blockquote {...props} className="text-gray-600 border-l-2 border-indigo-300 pl-5" />,
    ul: ({ node, ...props }) => <ul {...props} className="text-base list-disc" />,
    ol: ({ node, ...props }) => <ol {...props} className="text-base list-decimal" />,
    li: ({ node, ...props }) => <li {...props} className="text-base" />,
    hr: ({ node, ...props }) => <hr {...props} className="text-base my-2" />,
    code: ({ node, ...props }) => <code {...props} className="bg-indigo-300 border-indigo-400 border-2 p-1 rounded-md" />,
    img: ({ node, ...props }) => <img {...props} className="max-w-md" />,
};
